### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by nkostiai** [villelahdenvuo/CrazyJavaBubbles#1]
------------Katselmoitu versio ladattu 14.2.2014 klo. 20:00 -------------

Pelin koodi on varsin selkeää ja jäsenneltyä. Nimeäminen toimii ja harvoin jää pitkäksi aikaa miettimään, mikä kunkin metodin ja attribuutin varsinainen funktio on. Kommentoitia löytyy sieltä mistä pitääkin ja siinäkin, missä on harvasanaista, kertoo kaiken olennaisen.

Vastuu on jaettu luokittain selkeästi ja luokat on paketoitu intuitiivisesti omiin paketteisiinsa. Logiikan ja kälin erottamisessa on tehty esimerkkilistä työtä, huomattavasti parempaa kuin mitä allekirjoittajan räpellyksestä ikinä löytyykään. Logiikan testaus näyttää myös erittäin kattavalta. Virheiden käsittelyäkin on tarvittaessa harrastettu kivasti. Mainittakoon, että kaikki edellämainituista aspekteista ovat allekirjoittaneen projussa jääneet enemmän tai vähemmän hunningolle

Koska kritiikkiä on jostain puolipakolla väännettävä, niin mainittakoon että jokunen metodi iski lähinnä pituudessaan silmään. Näistä esimerkkinä ehkä SplashScreen#init, josta pystyisi esimerkiksi tuon kuplien generoinnin siirtämään omaan metodiinsa.
Myös esimerkiksi Application-luokan attribuutit olisi varmaan halutessaan voinut heittää johonkin apuluokkaan. Tämä nyt on kuitenkin lähinnä nillittämistä ihan nillittämisen ilosta, eikä välttämättä vastaa edes varsinaisia best practiceja. Kaikkiaanhan tämä koko projekti on mainiota työtä ja hyvästä koodaajasta kertonee jo sekin, että katselmoinnista oli taatusti sekä hyötyä että iloa enemmän katselmoijalle kuin itse kohteelle.

Kaikkiaan: Clean Code toimii, sinifunktion parametrit on castattu doubleiksi ja katselmoijan alemmuuskompleksi jyllää.

![thumbs-up-computer-kid-gif_zps11d45fe6](https://f.cloud.github.com/assets/6378104/2174758/e514e7de-95b5-11e3-97e5-a4217405ee66.gif)

Peace out.

Your friendly neighborhood NikG

**Comment by villelahdenvuo** [comment]
:+1:
